patterns:
  node:
    default: '/[node:title]'
    bundles:
      news:
        default: '/nyheder/[node:title]'
      overview_page:
        default: '/[node:menu-link:parent:title]/[node:title]'
      page:
        default: '/[node:menu-link:parent:title]/[node:title]'
  taxonomy_term:
    default: '/[term:vocabulary]/[term:name]'
  forum:
    default: '/[term:vocabulary]/[term:name]'
  user:
    default: '/users/[user:name]'
langcode: da
